services:
  db:
    image: postgres:latest
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


